### ISSUE TITLE
Method to apply custom metadata to data assets

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-codeocean-utils#2]
# User story
As a user, I want to run a method to easily update custom metadata.

# Acceptance criteria
- [ ]  When a user runs a method with arguments with a supplied set of data asset IDs, these assets will have `modality`, `subject id`, `platform`, `collection date`, `institution`, and `data level` filled out correctly.
- [ ] ~The values for these fields should come from the document db API.~
- [ ]  There is an option to print out the changes to a log file (default to True)
- [ ]  Appropriate docstrings and unit tests

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by Sun-flow** [comment]
This functionality is being fulfilled in the repo: https://github.com/AllenNeuralDynamics/CustomMetadataTagger

A codeocean capsule exists that is fulfilling this request. How can I perform a review on this work @dyf @jtyoung84 ?

**Comment by jtyoung84** [comment]
@Sun-flow I think the plan was to put the core logic in this repository. We can add a method similar to the APIHandler update_tags function and import this library as a dependency in the CustomMetadataTagger capsule. By maintaining the core logic here, we can re-use the function in other capsules and pipelines that are adding CustomMetadata to created data assets. I can update the acceptance criteria to remove the mention of document db. The CustomMetadataTagger capsule can pull the information from the different places and use a method here to combine the information.

**Comment by jtyoung84** [comment]
Closing this out for now
